spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: internetkyoomin0115@gmail.com
    password: dkxnfdfgtzofkspn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

